### ISSUE TITLE
estimator が落ちるようになった

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#394]
何も変えてないのに落ちるようになった。
```
START RequestId: aaacfbbc-b199-4072-bdde-c8a8307d71fc Version: $LATEST
Fetching dataset from 332 contests.
Expecting value: line 4 column 1 (char 3)
[ERROR] ValueError: not enough values to unpack (expected 2, got 0)
Traceback (most recent call last):
  File "/var/task/function.py", line 317, in handler
    results = run(target, overwrite)
  File "/var/task/function.py", line 281, in run
    user_results_by_problem, standings = fetch_dataset_for_contest(contest, existing_problems)
END RequestId: aaacfbbc-b199-4072-bdde-c8a8307d71fc
REPORT RequestId: aaacfbbc-b199-4072-bdde-c8a8307d71fc	Duration: 624.53 ms	Billed Duration: 700 ms	Memory Size: 256 MB	Max Memory Used: 76 MB	Init Duration: 347.13 ms	
```

**Comment by amylase** [comment]
😇 
ログインしてない状態だと `https://atcoder.jp/contests/{}/standings/json` にアクセスしてもログインページにリダイレクトされるようになったみたいです。

**Comment by kenkoooo** [comment]
みたいですね、やめてくれ〜〜〜

**Comment by kenkoooo** [comment]
とりあえず適当なアカウント作って環境変数にID/PASS入れて取る感じはどうでしょう？

**Comment by amylase** [comment]
よさそう。公式サイドにも了解をとったほうがよさそうですかね？　原則的には大量の機械的アクセスがあんまり嬉しくないという意思表示に思えるので。

**Comment by amylase** [comment]
アカウントを作って通知すれば向こうで問題があったときも調べやすそうなので

**Comment by kenkoooo** [comment]
そうですね。一応聞いてみますね。

**Comment by kenkoooo** [comment]
okらしいので、このissueをやる人は適当なアカウントを作って教えてください。

**Comment by kenkoooo** [comment]
fixed
