### ISSUE TITLE
Error in scraping submissions

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#45]
```
2018/02/01 15:06:10.843 ERROR - [com.kenkoooo.atcoder.scraper.SubmissionScraper] Catching
scala.MatchError: /contests/arc027/tasks/ (of class java.lang.String)
        at com.kenkoooo.atcoder.scraper.SubmissionScraper.$anonfun$scrape$3(SubmissionScraper.scala:37) ~[atcoder-problems-assembly-0.1.jar:0.1]
        at scala.util.Try$.apply(Try.scala:209) ~[atcoder-problems-assembly-0.1.jar:0.1]
        at com.kenkoooo.atcoder.scraper.SubmissionScraper.$anonfun$scrape$2(SubmissionScraper.scala:30) ~[atcoder-problems-assembly-0.1.jar:0.1]
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234) ~[atcoder-problems-assembly-0.1.jar:0.1]
```

**Comment by kenkoooo** [comment]
dup #50
